### ISSUE TITLE
SwiftLint path should be configurable on a per-project basis

### ISSUE THREAD

**Issue by bealex** [bealex/SwiftLintAppCode#38]
What steps will reproduce the problem?

1. Set the SwiftLint path (Tools | SwiftLint Inspections) in a project.
2. Switch projects and change the SwiftLint path.
3. Switch back to the first project.
4. Observe that the SwiftLint path was also updated for this project.

What is the expected result?

If SwiftLint is installed into the project using a package manager such as CocoaPods, Carthage or swift-package-manager, it should be possible to configure the SwiftLint path on a per-project basis (since versions may differ).

What happens instead?

Right now, AppCode only supports a global installation of SwiftLint.

**Comment by martinmose** [comment]
I vote for this as well. I would have expected that you could specify a relative path for "SwiftLint path" in Tools -> SwiftLint like: "./Pods/SwiftLint/swiftlint" but it doesn't seems to work (or otherwise I can't figure out how).
See: https://www.jetbrains.com/help/objc/absolute-path-variables.html?showChildren

**Comment by bealex** [comment]
Please check after updating to 1.13 (update should be available after JB review)
